### ISSUE TITLE
Implement Location list/card in play page

### ISSUE THREAD

**Issue by siraom15** [siraom15/spy-fall-client#14]
Implement Location list/card in play page

**Comment by siraom15** [comment]
doing

**Comment by alenros** [comment]
The current implementation is not responsive: on mobile the text overflows, and should probably be centered.
![Screenshot_20220409-110638_Firefox](https://user-images.githubusercontent.com/13719696/162562814-63bd2447-fe80-4e70-a8b4-109333ef9cb8.jpg)

**Comment by siraom15** [comment]
Thank you for your information.👨‍💻

**Comment by siraom15** [comment]
Fixed!

**Comment by alenros** [comment]
Works on my device. I think the issue can be closed.
