### ISSUE TITLE
server status obscures room code

### ISSUE THREAD

**Issue by alenros** [siraom15/spy-fall-client#16]
On mobile,during a game  the room code is obscured, even when scrolling
![Screenshot_20220409-112052_Firefox](https://user-images.githubusercontent.com/13719696/162563262-ae153045-da75-4c6f-94fe-eb969778c2e9.jpg)

**Comment by siraom15** [comment]
can you fix that? 
I think it should only show when server error.
if connected server it will fade out and disappear.

Edit on Component file: ServerStatus.vue
